version: "3.8"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes: #adicionando volume 
      - ./app/documents:/usr/src/app/app/documents
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck: # Verifica o estado
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      retries: 10
      timeout: 5s
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
